### ISSUE TITLE
bug: "Use Model" from the Hub fails to launch full Threads screen with Right Panel

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1042]
**Describe the bug**

**To Reproduce**
1. Go to Hub
2. Click "Use" for an already Downloaded model
3. Jan goes to a zombie "Threads" screen where unable to type in Input box, no Right Panel

**Screenshots**

Click "Use" for a downloaded model
![image](https://github.com/janhq/jan/assets/101145494/438e40ae-1adc-41e6-9ab1-cd3ad4c95272)

Zombie screen (unable to type in Input box, no Right Panel)
![image](https://github.com/janhq/jan/assets/101145494/9f99691a-2f40-4c02-98bc-fe0ba312083d)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - 16gb RAM, no GPU

**Additional context**

**Comment by 0xSage** [comment]
I'm experiencing a variation of this issue.

To repro: 
1. Click on use model (not currently active) in the Hub
2. It takes me to a previous thread, while starting the model
<img width="1302" alt="image" src="https://github.com/janhq/jan/assets/69952136/18bb9e5c-31fb-49cc-891c-9d7d800348d4">
3. The problem is that the UI shows the new model in the previous thread. 

I expected: 
1. Click on `use`
2. Land in a NEW thread
3. Wait for model to start.

Should be a simple fix hopefully

**Comment by louis-jan** [comment]
@namchuai: spawn new thread

**Comment by namchuai** [comment]
created a PR #1103 

Not really a bug since it's not being implemented. Definitely not a simple fix lol
