### ISSUE TITLE
bug: User rm -rfs the /model file, app is stuck in broken state

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#1072]
**Describe the bug**
User deleted the model file in the` jan/models` folder (not using `delete` button in the app) but still can choose in Jan app.

**Desktop**
 - OS: Windows
 - Version 0.4.2
 
**To Reproduce**
1. Go to jan/models/model_folder
2. Delete a downloaded model
3. Back to Jan app
4. Chat -> See error

**Expected behavior**

**Screenshots**
![image](https://github.com/janhq/jan/assets/64120343/66994566-d7da-4ec1-bf28-c8d9ff60ad72)

**Comment by hahuyhoang411** [comment]
Close for now

**Comment by tikikun** [comment]
still a valid UX issue, please keep open

**Comment by louis-jan** [comment]
App reads from model.json "state": "ready" mean the model is ready. There would be an enhancement #1039 that could also address this

**Comment by 0xSage** [comment]
Good issue. Can be solved with #1052

**Comment by louis-jan** [comment]
I want to sneak in one more case of deleting a model. The threads created with the deleted model should display a proper error handling message. Otherwise sending new messages to this thread will block the other threads.

<img width="1572" alt="Screenshot 2023-12-21 at 11 35 32" src="https://github.com/janhq/jan/assets/133622055/f3c9cd35-c372-4a66-aaad-914a569067fb">
