### ISSUE TITLE
docker compose network should not have jan_community

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#124]
## Problem

- docker-compose.yml still has networks `jan_community`, but we no longer have a community edition, only Jan
- Why do we have static IPs? (172.20.0.15)

**Comment by hiento09** [comment]
- Let me rename the network
- There are 2 reasons why we need static ip here
  - First, the hasura seed apply configuration is hard code as localhost so I need the ip address of real graph engine and override the localhost here
![image](https://github.com/janhq/jan/assets/136591877/c6f468ba-e0d1-424b-85ff-8d26057d47f8)

  - Second, 1Keycloa1k need to expose to user for authentication, and its domain will be set in `web-client` because we are using docker-compose, if I put `localhost` in `web-client`, it will be `web-client` ip address itself. So I need to put the ip address of keycloak here (which are expose to localhost port 8088), and override the localhost ip address locally.  
![image](https://github.com/janhq/jan/assets/136591877/e66d1083-31e8-46c9-84ee-e86b2bc1241a)

**Comment by hiento09** [comment]
imo, Docker-compose is used for testing only, so it should not a problem with static ip address here @dan-jan. We just need a well document for that.
