### ISSUE TITLE
feat: Clearer message for Nitro related error

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#1278]
**Problem**
- Users using Jan might face different problems related to Nitro:
  - https://github.com/janhq/jan/issues/1243
  - NVIDIA GPU related issue
  - OOM for RAM/ VRAM
  - Mac related issue: https://github.com/janhq/nitro/issues/267
- The current indicator to user now is only "Failed to fetch" makes it hard to debug

**Success Criteria**
- Tree-based error for Nitro with proper error handler and alert. The generic case should be: "Nitro error" and guidance to file issue with template (OS, reproducible steps)

**Additional context**

**Comment by sobkiso** [comment]
https://redccshop.mysellix.io/product/xchkrobot-source-code

**Comment by tikikun** [comment]
There are several potential issues and errors that can arise from the provided code. Let's break them down:

1. **Unverified JSON Input**: The code assumes that the JSON input (`jsonBody`) contains specific fields (like `"mmproj"`, `"llama_model_path"`, etc.) and directly uses them without verifying if they exist or are of the expected type. This can lead to runtime exceptions if these fields are missing or of an incorrect type.

2. **Hardcoded Default Values**: The code uses hardcoded default values for various parameters (like `100` for `n_gpu_layers`, `2048` for `n_ctx`, etc.). While this is not inherently an issue, it can lead to unexpected behavior if these defaults are not suitable for all use cases.

3. **Thread Safety**: The function `loadModelImpl` modifies the state of the `llamaCPP` object. If this function is called from multiple threads simultaneously, it can lead to race conditions unless proper synchronization mechanisms are in place.

4. **Error Handling in `loadModelImpl`**: The function does not handle exceptions that might be thrown by its operations, such as JSON parsing or model loading. This can cause the application to terminate unexpectedly in case of an error.

5. **Model Reload**: The `loadModel` function checks if the model is already loaded and returns an error if it is. However, it does not provide a mechanism to reload or refresh the model without restarting the service.

6. **Dependency on Global State**: The code uses `std::thread::hardware_concurrency()` to determine the number of threads. This is system-dependent and may not always provide the optimal number of threads for the application.

7. **Potential Memory Leak with Threads**: The code starts a new thread (`backgroundThread`) but does not show any mechanism for joining or safely terminating this thread. This can lead to a memory leak or dangling thread issue.

8. **Use of Preprocessor Directives**: The use of `#ifdef GGML_USE_CUBLAS` without an `#else` clause means that if `GGML_USE_CUBLAS` is not defined, the `params.mul_mat_q` variable is left uninitialized. This can lead to unpredictable behavior.

9. **Lack of Return in Non-Void Function**: In `loadModel`, there is no return statement after the callback is invoked. This is more of a style issue since the return type is `void`, but it can be confusing.

10. **No Validation of `req`**: The `loadModel` function does not validate the `req` parameter before dereferencing it. If `req` is null, it can lead to a null pointer dereference.

Addressing these issues would involve adding proper error handling, input validation, thread synchronization, and possibly refactoring some parts of the code for better clarity and reliability.

**Comment by tikikun** [comment]
Asides from that most of the issues on the repos are:
- Accelerator issues (CUDA metal etc... cannot be found)
- Glibc issues (not compatible with linux version)
