### ISSUE TITLE
Let's add everything that a person created in 1 hour of time ? 

### ISSUE THREAD

**Issue by SyntaxEvg** [janhq/jan#1593]
## Motivation
- 
https://www.youtube.com/watch?v=CUjO8b6_ZuM 
https://github.com/Leon-Sander/local_multimodal_ai_chat
## Specs
- 

## Designs
[Figma](link)

## Tasklist
- [ ] 

## Not in Scope
-

**Comment by imtuyethan** [comment]
Thanks for your suggestion @SyntaxEvg. We are working on this at the moment, starting with RAG first. You can see the epic progress here:  https://github.com/orgs/janhq/projects/5/views/16?pane=issue&itemId=47926046

As we are a small bootstrapped team, everything cannot be developed very fast. That's why we open-source & welcome all engineers to contribute. Anything you want to build on your side & collaborate with us, please contact us on Discord, thank you! <3
