### ISSUE TITLE
bug: path not relate to content 😅 

### ISSUE THREAD

**Issue by TC117** [janhq/jan#1679]
**Describe the bug**
On doc page https://jan.ai/guides/integrations/continue/#tag/Threads/operation/deleteThread
the path was delete Thread but the content is the integration example: 
![image](https://github.com/janhq/jan/assets/19384189/ea0accaa-56af-4dc1-a7e1-d352b92f7247)

**Comment by 0xSage** [comment]
Good catch, thanks!

**Comment by hieu-jan** [comment]
Hi @TC117, thank you for reporting it. I think the path for delete thread is `https://jan.ai/api-reference/#tag/Threads/operation/deleteThread` 

For your report link: `https://jan.ai/guides/integrations/continue/#tag/Threads/operation/deleteThread` Because it doesn't have any tag #, so it will return normally link https://jan.ai/guides/integrations/continue without the redundant tag.
