### ISSUE TITLE
bug: Undefined issue

### ISSUE THREAD

**Issue by aha097** [janhq/jan#1871]
**Everytime I started the model, it turned out an undefined issue**

**Screenshots**
<img width="1190" alt="截屏2024-01-30 17 49 59" src="https://github.com/janhq/jan/assets/119548675/985611c2-d637-43d7-9028-c3bdfcff0bf1">

**Environment details**
- Operating System:  MacOS Sonoma 14.2.1
- Processor:Apple M1
- RAM: 16GB

**Comment by JarkMark** [comment]
![image](https://github.com/janhq/jan/assets/131581978/581e8f75-9a2b-4ae2-8af0-661f282611a7)

Windows have same problem

**Comment by Van-QA** [comment]
Please help us by providing the app.log for troubleshooting: https://jan.ai/troubleshooting/how-to-get-error-logs/
Note that there have been multiple entry points that could cause the undefined popup so far:
- Corrupted model
- Port in use
- Non-latin characters in path
...

You can try this approach to start Nitro manually:
1. Try wiping the Jan folder, and reopening the Jan app to see if the issue is resolved.
2. Go to jan folder / extensions / @janhq / inference-nitro-extension / dist / bin / your OS / nitro => try to start the nitro manually and see if any errors are displayed.
3. Resolve errors from your side until Nitro is properly started with no issues.
4. Reopen and double-check the Jan app again.

**Comment by cryptyck** [comment]
I just had the same error, which an apparent OOM caused. Although plenty of VRAM was available, I had to clear out some system memory, and then the issue was solved.

**Comment by aha097** [comment]
After checking, I find my problem is due to the model download from the Jan Hub. The model download from the Jan Hub is not fully correct, it just download partially without any warnings, so I download the model from website directly instead and it solve the problem.
