### ISSUE TITLE
docs: NVIDIA GPU guideline

### ISSUE THREAD

**Issue by cccman9194** [janhq/jan#1946]
I was solved RTX Series issue.
Firstly update NVIDIA graphic driver.
Next, install NVIDIA CUDA driver.
Installation of CUDA is essential.

https://developer.nvidia.com/cuda-downloads

**Comment by Van-QA** [comment]
@hieu-jan to add this to the guideline

**Comment by k9bbzJavftZaqAqSW3dY** [comment]
Hi, sorry I don't know where to put this but on my arch, the described steps were not enough because the program looks for libcudart.so.11.7, whereas I'm on cuda 12. While I could have downgraded cuda, it was requiring a lot of recompiling. In the end I got away symlinking my libcudart.so from version 12 as `libcudart.so.11.7` inside cuda's folder (use the find command, it's different places for different distros). Add the cuda path to the environment for good measure: `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/cuda/or/wherever/it/is`. Logout and login, and you're good to go. I had no issues! Thanks for this fantastic program!

**Comment by cccman9194** [comment]
I have a question. Generally, i'm using Jan.ai to study my local documents.
But can't use Sbert like GPT4ALL.
Can you add plugin next Version of Jan?

2024년 2월 7일 (수) 오전 11:45, Ashley ***@***.***>님이 작성:
