### ISSUE TITLE
Structure plugin metadata

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#214]
Louis — Today at 12:42 PM:
forgot that we need to structure the plugin metadata which could help for that case. Plugin's author, url, ref, image... are needed for further our forked-npm repository. @Nicole could you please help on this ⬆️  (plugin metadata) 
have this finalized could help plugin author to not update plugin metadata when we release plugin mkp / npm repo

**Comment by 0xSage** [comment]
@louis-jan can we just use this: https://github.com/obsidianmd/obsidian-sample-plugin/blob/master/manifest.json

Or did you mean something else by "plugin metadata"?

**Comment by luiyen** [comment]
Ye, this is. But we might want to add a few more optional fields such as icon, pluginPack, dependencies, pricing 🤣

https://code.visualstudio.com/api/references/extension-manifest

**Comment by 0xSage** [comment]
> Ye, this is. But we might want to add a few more optional fields such as icon, pluginPack, dependencies, pricing 🤣

I see your point. Can we keep things simple in the beginning, i.e. omit pricing for now: 

```json
{
	"id": "sample-plugin",
	"name": "Sample Plugin",
	"version": "1.0.0",
	"minAppVersion": "0.15.0",
	"description": "This is a sample plugin for Jan. This plugin demonstrates some of the capabilities of the Jan API.",
	"author": "MeowMeowPants",
	"authorUrl": "https://twitter.com",
	"tags": "",
	"icon": "",
	"isDesktopOnly": false
}
```

Questions @louis-jan : 
- For dependencies, can't we auto infer that from the plugins' package.json?
- What is pluginPack?

**Comment by louis-jan** [comment]
@0xSage Metadata here is exactly package.json, I don't mean to distribute plugin metadata on other any other channels. 
You can ignore pluginPack, I just want to have something planned in the future where we support dependency as another plugin instead of just an npm module. e.g. Custom UI Plugin A needs Service Plugin A to be installed to work properly.

<img width="642" alt="Screenshot 2023-10-10 at 14 09 34" src="https://github.com/janhq/jan/assets/133622055/c797a707-7af3-4357-bc0a-da02b470b550">

**Comment by louis-jan** [comment]
Ah yes @0xSage, please close
