### ISSUE TITLE
bug/feat: Windows uninstall should delete the Jan Data Folder

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#2377]
**Describe the bug**

**Steps to reproduce**
1. Windows > Add or Remove programs
2. Uninstall Jan
3. Jan Data Folder still persists after uninstallation

**Comment by Van-QA** [comment]
Additional Note:
- Currently, no folders or data are being removed when uninstalling the Jan app. Only the Jan app itself is deleted.
- This is why we have not documented any folders or data that users should expect to disappear after uninstallation.
- We will update this information once the removal process is implemented or if possible, please help us with a doc page to highlight that we are not removing any data yet, linking to this issue for reference @hieu-jan

**Comment by dan-jan** [comment]
I'm personally not sure if we should delete the Jan Data Folder if Jan is deleted. 
This data belongs to them, not to Jan = they may want to use the models, conversaions with different apps in the future

**Comment by 0xSage** [comment]
There should be an option to. And users can check/uncheck it.
Similar with their appdata/cache file.

**Comment by hiento09** [comment]
PR #2705 When a user uninstalls the Jan app via the Windows Control Panel, the following notification will be displayed:
![image](https://github.com/janhq/jan/assets/136591877/3bf923b1-0807-436a-b0bf-d990a78c0c49)

If a user changes the Jan Data folder, since this folder belongs to the user, it will not be deleted. cc @dan-jan , @0xSage , @Van-QA

**Comment by Van-QA** [comment]
> If a user changes the Jan Data folder, since this folder belongs to the user, it will not be deleted.

Note that reinstallation at this stage will be a clean install, Jan app no longer connected to the existing Jan data folder (that remain from the previous step)
Users will have to override the data manually if needed, which is why we need a correction of the message to 

`Do you also want to delete **default** Jan data folder at ... `

cc: @hiento09
