### ISSUE TITLE
4096Token quantity is too small

### ISSUE THREAD

**Issue by lv333ming** [janhq/jan#2387]
I'm asking this question too. 4096Token quantity is too small .  How to increase the number of tokens

**Comment by hahuyhoang411** [comment]
Hi @lv333ming , to increase the maximum context length for the model. Please adjust the `"ctx_len"` field in the corresponding `model.json` file.

Caution:
- When you increase `ctx_len`, please ensure that your VRAM/RAM is big enough to fit the model, otherwise it will crash.

Please reopen if you need any further help.
