### ISSUE TITLE
bug: download cannot resume after network interruption

### ISSUE THREAD

**Issue by lenzai** [janhq/jan#2479]
**Describe the bug**
Downloading models does not tolerate network interruptions
**Steps to reproduce**
0. turn on VPN
1. Go to 'Hub'
2. Select a model , e.g. 'mixtral'
3. Click on 'Download'
4. turn off vpn
5. wait 5 minutes
6. turn on vpn
7. download won't resume.

**Expected behavior**
When network comes back , resume download before 1 minute

**Environment details**
- Operating System: Mac OS 13.5.1 (22G90)
- Jan Version: 0.4.9
- Processor: Apple M1 Max
- RAM: 32GB

**Additional context**
I am in China, cannot download models without VPN

**Comment by Van-QA** [comment]
I can reproduce the, but not sure if we are able to resolve it. cc @louis-jan

**Comment by louis-jan** [comment]
Download resuming is not planned any time soon since models are downloaded from third-party sources such as Hugging Face, not from our sources. Even Chrome or modern browsers are likely to restart the download from the beginning if your network changes or if there is idle time after a couple of minutes
