### ISSUE TITLE
bug: App.log filling hard drive

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2485]
**Describe the bug**
Quoted from Hords

> Hi, I was wondering if there's a way to disable the app.log in Windows? I run the API server and after quite a bit of use I end up filling up my hard drive due to the size of the app.log file. I can clear it, but then it ends up happening again, so it'd be nice to prevent it in the first place. Thanks!
> Hi, I'm using 0.4.9 currently. testing it now and I'm up to 190GB for my log file after running it for around 4 hours, constantly querying the api server. I looked at the code, and if I read it right, it looks like this fix cleans up after 7 days? Thanks
https://discord.com/channels/1107178041848909847/1220501334508175360

**Environment details**
- Operating System: Windows 10
- Jan Version: 0.4.9

**Comment by Hords** [comment]
Hi, it sounds like it currently may only clean up the logs upon Jan opening, but I leave it open running the API server and so it seems to never clean up. Thanks!

**Comment by 0xSage** [comment]
Hmm, I'm wondering what the best UX here is. 

A few not so great suggestions - super open to what community says here. 

1. Cap app.logs at `n lines` or `n mb` maximum. Beyond which, we auto clear logs. This way, logs never bloat past xGB.
2. Let users disable logs (as OP suggests)
3. We might consider disabling the current hack of clearing every n hours, because of the previously stated reasons and because logs can bloat within just a few minutes on a bad error.

**Comment by Van-QA** [comment]
looking good on Jan v0.4.10-371 ✅
