### ISSUE TITLE
Discussion: [API model selection]   

### ISSUE THREAD

**Issue by sfz009900** [janhq/jan#2600]
For example, I want to use the native API for a translation software, but the model selection of the translation software is only gpt3.5 or gpt4, what should I do :)?

**Comment by Propheticus** [comment]
My expectation: ask the translation software to implement a choice to use (local) Open AI stand-in APIs. Any local app that follows the API specification of Open AI, like Jan, could then work.
But: commercial products with a SLA / service commitment will probably limit the options they offer to those that are of a high enough 'production quality' to limit the amount of support cases they get with issues and questions caused by 3rd party dependencies.

**Comment by imtuyethan** [comment]
> For example, I want to use the native API for a translation software, but the model selection of the translation software is only gpt3.5 or gpt4, what should I do :)?

We are moving forward with more inference engines like OpenAI, Groq, Mistral, OpenRouter,... (see docs here: https://jan.ai/docs/remote-inference/openai)
