### ISSUE TITLE
feat: opt out from sending usage analytics

### ISSUE THREAD

**Issue by dzlab** [janhq/jan#2759]
**Problem**
It seems that umani.is is used to collect analytics as I did see requests sent to http://eu.umami.is/api/send

Can you add an option to opt out from analytics?

**Success Criteria**
Have a toggle or configuration to opt out from sending any sorts of analytics

**Comment by mobile-appz** [comment]
@henryh0x1 henryh0x1 can you please share what metrics this is tracking?

**Comment by dzlab** [comment]
@mobile-appz I don't know what metrics were tracked, I just saw couple of requests when opening the developer console.

**Comment by mobile-appz** [comment]
> @mobile-appz I don't know what metrics were tracked, I just saw couple of requests when opening the developer console.

Thanks for the info. I'm not seeing any network requests when using the MacOS app and entering prompts but don't know how to see this in the developer console.

**Comment by imtuyethan** [comment]
Hey @dzlab, thanks for bringing this up! We hear you on the privacy concerns. 
We're actually planning to remove Umami analytics completely within the next 3 releases. 

Just to give you some background - we initially added Umami to get a basic idea of our Daily Active Users (DAU). It helps us understand how many folks are actually using Jan and plan our resources better.
But no worries, we've already turned off most of the analytics options. We're only keeping the bare minimum, anonymous stuff like DAU counts. Nothing that could identify individual users.
We totally get that privacy is super important, especially for a tool like Jan. That's why we're working on phasing it out entirely. Appreciate your patience while we wrap that up!
Let me know if you have any other questions or concerns. We're always open to feedback from the community! 👍

**Comment by 0xSage** [comment]
@louis-jan didn't we remove all umami stuff already? If so , pls close issue. Thank you 🙏

**Comment by imtuyethan** [comment]
> @louis-jan didn't we remove all umami stuff already? If so , pls close issue. Thank you 🙏

We haven't removed Umami.

**Comment by imtuyethan** [comment]
Dup of #3503

**Comment by imtuyethan** [comment]
https://github.com/janhq/jan/issues/3119

We will allow users to opt-in & opt-out analytics in v0.5.11
