### ISSUE TITLE
feat: add use button after adding cloud model api key

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#3073]
### #

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

its so many clicks to go from adding api key > chat page > new conversation > select model > select claude/cloud model > start chatting. 

### Describe the solution

<img width="948" alt="image" src="https://github.com/janhq/jan/assets/69952136/0d002e0c-b02a-4f0f-9910-7db65a31bd20">

add use button after api key is input

### What is the motivation / use case for changing the behavior?

yes

**Comment by imtuyethan** [comment]
@0xSage Ah i think it doesn't make sense as what model would be chosen after users click use. 
Previously we have API key management pop-up directly for users, it was removed because we want it to be more programmatically & don't need to maintain too many components. 

![Screenshot 2024-08-27 at 6 31 38 PM](https://github.com/user-attachments/assets/8f5e2d78-d2de-4b8a-9449-c3df4afc08c3)

https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=8124-48999&t=tP4XUtyZk6tTrQHR-4
