### ISSUE TITLE
feat: render code, indents, markdown for user inputs

### ISSUE THREAD

**Issue by tchopra17** [janhq/jan#3358]
### #

- [ ] I have searched the existing issues

### Current behavior

Code pasted in with indents renders with 0 indents. However, when going to edit the input, the indents render.

### Minimum reproduction step

Paste code in with indents

### Expected behavior

Code or anything with indents should render correctly for input as well as output. Markdown support would be nice too. 

### Screenshots / Logs

<img width="934" alt="Screenshot 2024-08-12 at 10 56 44 PM" src="https://github.com/user-attachments/assets/c4f06468-220d-4899-b7b4-a7d5d75fb97d">
<img width="955" alt="Screenshot 2024-08-12 at 10 56 41 PM" src="https://github.com/user-attachments/assets/71ad773d-3546-457a-865c-2dc39c09bc6a">

### Jan version

0.5.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by louis-jan** [comment]
@imtuyethan feature request. Need to think thru it carefully. The are issues in the past as I remember cc @urmauur

**Comment by batonac** [comment]
Is this an appropriate place to track code-snippet formatting on user inputs as well?

Currently, snippets are formatted in the outputs but not the inputs:
![image](https://github.com/user-attachments/assets/0a7598c1-ecf5-4704-af19-12fa03b47a4c)

**Comment by imtuyethan** [comment]
This is not a bug, i'll close this & follow up on https://github.com/janhq/jan/issues/3739 instead

**Comment by 0xSage** [comment]
Still an issue, reopening

**Comment by imtuyethan** [comment]
We will support this, but it will be under Advanced Settings or Appearance settings, as previously we have received some reports about how some people tried to do some code injection & which could break the app.

Related ticket: https://github.com/janhq/jan/issues/3739

**Comment by 0xSage** [comment]
> We will support this, but it will be under Advanced Settings or Appearance settings, as previously we have received some reports about how some people tried to do some code injection & which could break the app.
> 
> Related ticket: #3739

@imtuyethan This is not a settings feature. Let's stop shoving things into settings, when they should just be handled by default.

I'd like @urmauur to investigate this issue more and figure out how we can do this in a secure way. If the solution involves injection vulnerabilities, then it was never the correct solution.

**Comment by louis-jan** [comment]
Hi @tchopra17, regarding the indentation issue, we will fix it. Since it's a raw text, it's important to maintain its original format.

@batonac I also prefer the Markdown rendering on sent messages. However, others might not (we are sharing the same markdown rendering technique) https://github.com/janhq/jan/issues/1849. But it's likely we fixed the HTML parsing issue #1939 so, proceeding with the sent message is fine.

@0xSage @imtuyethan @urmauur I think the previous implementation of Markdown support in the input is not correct, as we share the same dependency. It should preserve the raw content and merely apply some type of highlighting techniques. Otherwise, it introduces a rather poor UX and obstructs the input. For instance, other markdown editors offer two modes: write and preview (to simplify the input since it's not the Markdown Editor).

**Comment by urmauur** [comment]
@0xSage  @louis-jan  @imtuyethan  Alright then, we’re good to go. I’ll move this to the scheduled Kanban.

**Comment by imtuyethan** [comment]
Tested 0.5.6-665 with 
- [x] Code blocks with syntax highlighting
- [x] Lists (ordered and unordered)
- [x] Bold and italic text
- [x] Links
- [x] Blockquotes
<img width="769" alt="Screenshot 2024-10-22 at 3 21 57 PM" src="https://github.com/user-attachments/assets/52506498-7381-45ee-8900-fd420c1b5ce3">
<img width="783" alt="Screenshot 2024-10-22 at 3 21 52 PM" src="https://github.com/user-attachments/assets/d724656a-e162-4baa-9281-92f5620503c0">

It works well on my end:
<img width="806" alt="Screenshot 2024-10-22 at 3 22 05 PM" src="https://github.com/user-attachments/assets/842f6950-fe24-49ce-bcc5-9a46090b3f5e">
