### ISSUE TITLE
bug: Inference on CPU is slower on Jan 0.5.3

### ISSUE THREAD

**Issue by nguyenhoangthuan99** [janhq/jan#3549]
**Problem**
I have Nvidia GPU in my PC, but when I want to run it with CPU with latest Jan (0.5.3), the speed is decrease significantly. Some machine with only CPU also met this problem.

**Explanation**
In 0.5.3, when your device has Nvidia GPU, we will delivery the non-AVX + Cuda acceleration version, since even when offload half of layers to GPU, the performance doesn't decrease too much. This update help us to serve more CPU architecture that doesn't support AVX2 instruction (default in prevs version). But when you run every thing in CPU, the performance will drop significantly

**Solution**
We have two cases to handle:
- With GPU acceleration:
     - we will bundle all: NoAVX + Cuda binary and AVX2 + Cuda binary  (this will require more storage on your device ~150Mb for each AVX option binary and ~400Mb for Cuda binary)
     - We go for a big epic - install engine in runtime, chose what version to install ( require more effort - time )
- CPU ONLY:
     -  Non-AVX + AVX + AVX2 + AVX512 for CPU only case (since they are small in terms of size)

**Comment by nguyenhoangthuan99** [comment]
Here is related issue in Discord:
https://discordapp.com/channels/1107178041848909847/1280482676532445194

https://discordapp.com/channels/1107178041848909847/1278728986226069504

**Comment by dan-homebrew** [comment]
@nguyenhoangthuan99 Can I try to articulate my understanding of this problem + the solution, based on my historical understanding and what you guys have posted in Discord the last few days. 

## Problem

- In 0.5.3, users who owned a Nvidia GPU but chose to only run inference using their CPU encountered a loss in token speed
- This is due to Jan, when detecting a GPU, uses a version of llama.cpp that is compiled with "No AVX, CUDA"
- The "No AVX" flag results in slower CPU inference, as llama.cpp does not take advantage of AVX-2 opcodes that are present in most post-2016 CPUs

## Why did we go to No AVX?

- Previously, Jan used to package a version of llama.cpp compiled with AVX-2 flags and CUDA support
- There was a particular subset of users (had Nvidia GPU, but old CPU with no AVX?) that were not supported
- These users could run 100% on GPU, but could not offload layers to CPU, nor run CPU-only inference

We did some performance testing on llama.cpp compiled for CUDA but no-AVX flags: 
- Performance did not drop much, because GPU was very fast
- We assumed that this group, with GPUs, would not do CPU-only inference
- This assumption turned out to be wrong (it is possible that many of them didn't know how to setup their GPUs for Jan)

## Questions

> we will bundle all: NoAVX + Cuda binary and AVX2 + Cuda binary (this will require more storage on your device ~150Mb for each AVX option binary and ~400Mb for Cuda binary)

From my understanding, we are planning to solve this by adding another llama.cpp version to Jan: 
- This will bloat Jan by another 150mb
- We will have `avx2-11.7.1` and `avx2-12.1`?
- My understanding is that we already package a few versions of llama.cpp (Windows = 353mb, Linux = 351mb)
- https://github.com/janhq/jan/releases/tag/v0.5.3

However, by looking at the llama.cpp releases, I see that they go with a simpler heuristic: 
- They support 3 main CPU versions (i.e. no AVX, AVX-2, AVX-512)
- They support 2 main CUDA versions (i.e. 11 and 12)

![Image](https://github.com/user-attachments/assets/64c5babe-2b18-4fb7-afca-21be67f91454)

Alternative solution: can we use a CPU-optimized version of llama.cpp, when we detect that user is doing CPU-only inference?
- We detect if user is doing CPU-only inference (i.e. GPU is not active), or `ngl` = 0
- We use the `win-avx2` (or hell, even `win-avx512`) variant of llama.cpp

**Comment by louis-jan** [comment]
Roger that! @dan-homebrew. I am working on these now.

**Comment by Castafers** [comment]
I'm currently having this major issue myself.
I don't have extended knowledge on the topic unfortunately, however here are my specs.

**JanAI Version:** v0.5.3
**OS:** Arch Linux
**CPU:** Ryzen 7800X3D
**GPU:** RX 7800 XT (20GB DDR6 RAM)
**RAM:** 32GB DDR5
**Storage:** 2TB M.2
**Daily AI Model:** Llama 3.1

I would like to note, I am on purely AMD.
As far as I'm aware, AMD doesn't have CUDA at all, though I could be wrong.
