### ISSUE TITLE
idea: improvements on the chat UI elements

### ISSUE THREAD

**Issue by QuentinMacheda** [janhq/jan#3631]
### Problem Statement

The chat input's left and right margins are totally different from the chat body's. And personally, it doesn't feel user-friendly. It's actually kind of annoying... In addition, I think the chat body's left and right margins are way too big in full screen.

Here is a screenshot:

![image](https://github.com/user-attachments/assets/cd63e6b1-5054-437d-ba7c-7be0dc084ccc)

### Feature Idea

The idea would be to set the same chat input's left and right margins as the chat body's to get something more user-friendly. And in addition, I would reduce a little bit these left and right margins!

PS : I can take care of this, if needed!

**Comment by imtuyethan** [comment]
Hey @QuentinMacheda we did this because we wanted to improve the readability in Threads: https://github.com/janhq/jan/issues/3184
We also did a poll here on Discord & more ppl like the current improvement. 

However, since we received some feedbacks after the improvement, we think that users preferences are quite different, so we decide to let users to configure it on their own: https://github.com/janhq/jan/issues/3509. Please stay tuned & wait for the next updates!
