### ISSUE TITLE
bug: XML tags in chat completions are not rendered correctly 

### ISSUE THREAD

**Issue by abronte** [janhq/jan#3646]
### Jan version

0.5.3

### Describe the Bug

Jan does not render XML tags as such in chat completions. For example, prompting a model to put some data in some a tag like <result> you will see only the data and not the tag you instructed to put the data in.

### Steps to Reproduce

1. Open new thread
2. Prompt the LLM to put some text in an XML tags. ex w/ claude: "Put the string "Hello" in the xml tag <custom>"

### Screenshots / Logs

Jan's output:
![Screenshot 2024-09-12 at 10 24 04 AM](https://github.com/user-attachments/assets/854f681b-c3d2-46fb-888a-fba1c0f1f3a1)

Claude web UI for 
![Screenshot 2024-09-12 at 10 24 25 AM](https://github.com/user-attachments/assets/3838ec7f-5e6c-4e4f-b33a-12410187c4e8)
example:

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
Thanks for reporting this @abronte. 
This bug can be reproduced on my end (v0.5.4-640): ![Image](https://github.com/user-attachments/assets/ecbc47ec-308d-41c4-843a-4b16a266d1e7)
![Image](https://github.com/user-attachments/assets/36c3ab22-207a-4887-8e12-eb0d46cc3718)

We'll look into the root cause & fix it in upcoming releases.

**Comment by dan-homebrew** [comment]
This is likely due to our renderer - shifting it to @urmauur. 

I am putting this in Sprint 21, but it may be pushed back depending on Jan's backlog.
