### ISSUE TITLE
bug: LlaVa 7B responds as though I've provided JSON data

### ISSUE THREAD

**Issue by erayerdin** [janhq/jan#3658]
### Jan version

0.5.3

### Describe the Bug

I've downloaded LlaVa 7B and, to test it, I've sent a simple hello message, and it responded with:

```plain
The user provided a JSON object containing a "name" field and a "type" field. The "name" field is a string, while the "type" field is a string as well. The "name" field contains the word "Rock". The "type" field contains the word "type".

Based on the provided JSON object, the "name" field contains a single word and the "type" field also contains a single word. The "name" field is a string, and the "type" field is a string. The JSON object is a valid representation of two pieces of data, a name and a type, but without additional context, it is difficult to determine the specific use case for this data.
```

### Steps to Reproduce

1. Download LlaVa 7B
2. Write a message.
3. Get the weird response.

### Screenshots / Logs

![image](https://github.com/user-attachments/assets/58ffb7fc-2f59-47bb-8874-f75f375c956d)

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

**Comment by imtuyethan** [comment]
## Tested on:
Linux:
> 107 (test-ubuntu-app-cpu-2)

Mac:
> Operating System: MacOS Sonoma 14.2
Processor: Apple M2
RAM: 16GB


## Results:
On Linux: 
![Screenshot 2024-09-18 at 8 25 25 PM](https://github.com/user-attachments/assets/347dbf93-16cc-4075-a1ac-d0dc018e1f13)

On Mac: Its responses vary & not stable:

<img width="850" alt="Screenshot 2024-09-18 at 8 32 30 PM" src="https://github.com/user-attachments/assets/3f779ea5-72a5-4683-adfa-279eed177c8c">
<img width="821" alt="Screenshot 2024-09-18 at 8 32 54 PM" src="https://github.com/user-attachments/assets/d8c686f3-9fcc-4241-92fa-076b8e2b19c9">




High chances are this could be because of model performance, or our model settings are outdated? cc @louis-jan

**Comment by imtuyethan** [comment]
Related: https://github.com/janhq/jan/issues/3849
