### ISSUE TITLE
idea: User can export threads 

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3672]
### Problem Statement

https://discord.com/channels/1107178041848909847/1283890247888928931/1284099664207155222

Users often have long conversations with Jan (20-30 messages or more) that they want to save or share. Currently, there's no easy way to export these conversations. Manually copying and cleaning the text is time-consuming and impractical for longer threads. 

This feature would make it much easier for users to save, share, and review their conversations with Jan outside of the app.

### Feature Idea

Add an "Export Thread" option that allows users to save their conversations in HTML, JSON, PDF, or DOCX format.
- Add an "Export" button in the thread view for easy access.
- Allow users to choose the export location on their device.
- Allow users to choose format to export.

**Comment by imtuyethan** [comment]
<img width="510" alt="Screenshot 2024-09-23 at 11 29 40 AM" src="https://github.com/user-attachments/assets/3fac9531-0fa6-478d-a8fc-b738f027744f">

**Comment by 0xSage** [comment]
Wont do.
Since we already save conversations in files, it is already portable.

**Comment by lexspoon** [comment]
Here's a workaround that I put together today. It's possible to use the jq tool to convert the session to text. I used https://jqplay.org/ to access jq, but only because my test content was not sensitive. Install jq locally for serious use of this workaround.

You can find a .jsonl file underneath `data/threads` in your Jan data folder. The default data folder on Windows is `C:/Users/USERNAME/AppData/Roaming/jan`. This file has the contents of the thread in JSONL format.

Set the option `-r` on jq, to get raw output with the quotes removed.

Use the following jq query: `.role + ":\n" + .content[0].text.value + "\n\n"`

You can do a lot more by tinkering with the jq query, but I hope this gives people a start who had the same question.

For what it's worth, I think a simple version of "export" would really help Jan be even more useful than it already is. Sometimes people just want to share a thread with each other, and for an offline tool, a text format has some good tradeoffs. Text is the simplest format to implement, and it's universally compatible with all messaging systems.
