### ISSUE TITLE
bug: O1-Preview does not work because of: "Unsupported parameter: 'max_tokens' is not supported with this model.".

### ISSUE THREAD

**Issue by raphaelmosaic** [janhq/jan#3698]
### Jan version

v0.5.4-640

### Describe the Bug

When making a request using o1-preview or o1-mini, getting:

Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.
Jan’s in beta. Access troubleshooting assistance now.

Cannot change these model parameters settings.

### Screenshots / Logs

![c9e27463a830030ab08bc96bb4282cd72091d9cb9a9b4f320d722585b368bb33](https://github.com/user-attachments/assets/0c6c7fc7-c260-4f67-a4ca-eeb15cf8793c)

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
Thanks for reporting this @raphaelmosaic.

https://community.openai.com/t/why-was-max-tokens-changed-to-max-completion-tokens/938077/3


Looks like the new o1 series models (like o1-preview and o1-mini) use `max_completion_tokens` instead of `max_tokens`. We'll work on updating Jan to handle this smoothly.

For now, here's a quick workaround:
1. Open Jan's settings
2. Find the model settings for o1-preview or o1-mini
3. Look for `max_tokens` and change it to `max_completion_tokens`
4. Save your changes

This should get you up and running. We'll be pushing an update soon to handle this automatically.

**Comment by raphaelmosaic** [comment]
Changed this, still does not work. 
Please fix this properly asap as I am 100% one of many people who would use o1mini / o1preview via Jan and have this issue

![CleanShot 2024-09-23 at 22 09 30](https://github.com/user-attachments/assets/ef585896-92df-4bdb-a1c0-526c47641915)
![CleanShot 2024-09-23 at 22 09 37](https://github.com/user-attachments/assets/139e89d3-0c2b-4d72-b65c-d56ba6e5d71c)

**Comment by louis-jan** [comment]
Build containing bug fixes:
https://github.com/janhq/jan/actions/runs/11007851785

**Comment by imtuyethan** [comment]
I didn't see any changes @louis-jan 
<img width="987" alt="Screenshot 2024-10-01 at 7 44 12 PM" src="https://github.com/user-attachments/assets/cdbaa1c1-181b-4874-b75a-53e28ed95607">

<img width="946" alt="Screenshot 2024-10-01 at 7 42 21 PM" src="https://github.com/user-attachments/assets/3f657a89-d93a-4ccf-8a42-febdf0f29f02">

**Comment by imtuyethan** [comment]
![Image](https://github.com/user-attachments/assets/1ba036cd-45f4-4c49-9d2e-9fda445a979d)
