### ISSUE TITLE
epic: Jan integrates Cortex.cpp

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#3825]
## Goal

- Jan integrates Cortex.cpp and has a bug-free transition to Cortex.cpp
- Planning: #3690 

## Tasklist

- [ ] Eng Spec (copy over from #3690, replace this post)

## Previous Issues

- [x] #3633

**Comment by louis-jan** [comment]
# Migration Path:

1. App 0.5.8 opens
2. Return model list from cache (given users are on 0.5.7) -> function normally.
3. Scan JSON models (legacy logics - fresh install or older versions) -> function normally.
4. In background, app attempts to import models and merge with legacy downloaded models (failed to import models)
5. The app combines models returned by cortex.cpp and legacy JSON models. Cortex.cpp models are prioritized in case of the same ID.

# Changes
## Simplifed
Deprecated ModelFile. It's no longer relevant. Now, providers define Model, so it should manage how to run itself.

## Downloader
App proxies to cortex.cpp or app's downloader, depending on the cortex.cpp model support capability.

## Model Hub
App allows extensions to register models available for download in RAM. After downloading them, the models will have their yaml or json persisted along with the model files.

## Observability
- Introduced Watchdog helper to run the cortex.cpp server upon launch. It ensures that the cortex process runs with the application.
- All requests will be queued and run when server to come online, ensuring the UX remains the same. So there would be no asynchronous requests and server run introduced. E.g. Model import or start should not fail due to server not being online in time.
- So there would be no attempt to kill the cortex process on model start every time. It is just a stop and start model, so it will not block other API requests.

## Goals
- Updated from the older version to this version, models will be imported and run normally. Models are not imported will still able to run since we will attempt to do preflight before running.
- Users can download models or app proxies to cortex.cpp, or use the app downloader, depending on the cortex.cpp model support capability.
