### ISSUE TITLE
bug: We should be able to install & use Nightly, Beta & Stable versions at the same time

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3939]
### Jan version

0.5.7

### Describe the Bug

Right now we can only install & use Beta with Nightly/Stable versions at the same time.

### Expected behavior
Please fix & allow us to use 3 instances at the same as it's supposed to be.

**Comment by hiento09** [comment]
The nightly version has been around for a while and is currently sharing data with the stable version. From the CI side, we can do it, but it would result in the loss of existing user data for the nightly version. I think this requires additional implementation on the code side and would take 2-3 versions to handle properly. We need to discuss this ticket thoroughly as it's not a completely new app like the beta version.

**Comment by hiento09** [comment]
1. Force all current users onto the stable version. Here’s how:
- When we release version 0.5.8, I will disable the CICD for the nightly version and manually migrate the files for release 0.5.8 to the current nightly channel. This way, nightly users will receive a notification about the new update (since there’s no option for this, we have to do it manually).

2. The new nightly version will have a new update channel and new CICD:
- After setup is complete and to enable nightly users from step 1 to update to version 0.5.8, I will create a PR to adjust the CICD for the new app and update channel, similar to the beta version.
cc @imtuyethan @louis-jan @dan-homebrew @gabrielle-ong

**Comment by hiento09** [comment]
I will do 2 on tomorrow to unblock @imtuyethan
