### ISSUE TITLE
bug: [0.5.7] Models failed to load because of missing CUDA toolkit

### ISSUE THREAD

**Issue by bensojh1** [janhq/jan#3947]
I updated to v0.5.7 and now the models wont load and run
[app.log](https://github.com/user-attachments/files/17621518/app.log)

**Comment by imtuyethan** [comment]
Looking at these logs, there's a persistent error related to loading the Cortex engine:

```
ERROR Could not load engine: Could not load library "...engines/cortex.llamacpp/engine.dll"
The specified module could not be found.
```

- This appears to be an issue with the Cortex engine installation or path configuration
- CUDA is reported as not existing (`cuda: {"exist":false,"version":"12.0"}`)
=> Models failed with a 409 Conflict status because the engine isn't properly loaded

**To fix this, you should try:**
1. Reinstall Jan completely
2. Ensure CUDA 12.0 is properly installed on your system since you have an NVIDIA GPU

cc @louis-jan on another CUDA issue.

**Comment by imtuyethan** [comment]
@bensojh1 Can you check if you have installed CUDA toolkit and does Jan even ask you to install one? There should be a screen asking you to install.

**Comment by imtuyethan** [comment]
@bensojh1 When we release v0.5.8 https://github.com/janhq/jan/milestone/70 this Thursday (7 Nov 2024), missing CUDA issue will be solved as CUDA will be included by default.
