### ISSUE TITLE
bug: wrong max context with Command-R

### ISSUE THREAD

**Issue by Kep0a** [janhq/jan#4108]
### Jan version

0.5.9

### Describe the Bug

Locally imported Command-R 08-2024 GGUF has an incorrect maximum context length of 8192. 

Command-R 08-2024 has a maximum context of 128k.

Potential solution: locally imported model inference settings should all be able to be manually set

### Steps to Reproduce

1. Sym-link c4ai-command-r-08-2024-Q5_K_M.gguf
2. context length cannot be extended past 8192

### Screenshots / Logs

<img width="382" alt="Screenshot 2024-11-23 at 4 33 02 PM" src="https://github.com/user-attachments/assets/5544c30a-744b-4e26-ab72-bdca1d2ec917">

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
@Kep0a 
For self-imported models, you'll need to configure the model settings yourself since Jan won't be able to automatically detect the optimal settings.

![Screenshot 2024-11-24 at 7 49 53 PM](https://github.com/user-attachments/assets/1dc84f97-16af-4d41-b43b-ddebde3bf26c)

# How to manually configure model parameters

1. After importing your model, go to your `Jan Data Folder` (you can open it from `Settings` > `Advanced Settings` > `Jan Data Folder`)
2. Navigate to `models > imported` folder 

<img width="1042" alt="Screenshot 2024-11-24 at 7 52 56 PM" src="https://github.com/user-attachments/assets/98544217-0756-4d7b-8afa-f1d75b2ca2c7">


3. Find your model's yaml/json file and adjust the settings there
4. For context length specifically, look for `max_tokens` or `ctx_len` in the file


<img width="874" alt="Screenshot 2024-11-24 at 7 53 40 PM" src="https://github.com/user-attachments/assets/f7ce58f9-0db9-4585-b8d7-375114b64e6a">

The file shows all available parameters you can tweak, with helpful comments about valid ranges (like temperature: 0-1, etc). Just be careful editing these values - make sure they match your model's actual capabilities! 

_Tip: For better visibility, you can open the file with VS Code or any text editor that supports YAML syntax highlighting._

**Comment by Kep0a** [comment]
Thanks @imtuyethan !
