### ISSUE TITLE
bug: TypeError: _extensionManager_get.listThreads is not a function

### ISSUE THREAD

**Issue by longyongchao** [janhq/jan#4313]
### Jan version

0.5.12

### Describe the Bug

Unhandled Runtime Error
TypeError: _extensionManager_get.listThreads is not a function

Source
hooks/useThreads.ts (76:7) @ listThreads

  74 |   (await extensionManager
  75 |     .get<ConversationalExtension>(ExtensionTypeEnum.Conversational)
> 76 |     ?.listThreads()) ?? []
     |       ^
  77 |
  78 | console.log('Available extensions:', extensionManager.listExtensions())
  79 |
Call Stack
Show collapsed frames

### Screenshots / Logs

![image](https://github.com/user-attachments/assets/b67c0aee-fed8-445c-b8b1-61d578a14ced)

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by louis-jan** [comment]
Hi @longyongchao, since you're building from source, without development version bump (package.json), app will not install latest extensions, so that issue is about mismatching versions between the current development version and installed extensions.

1. You can delete app extensions in app data folder.
2. Change the app version in package.json (electron > package.json)
