### ISSUE TITLE
UI tweaks request for Jan Desktop App (v.0.3.1)

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#541]
I have some UI requests, would like to open up for discussion:

## Increase Font Size, Contrast (for readability?)

- I feel like a boomer for asking this, but I find myself `CMD-+` for both https://jan.ai and Jan Desktop app
- Can we consider making font sizes a big larger?
- Can we consider making font color a bit more high contrast for readability?

## Decrease Line Heights

- Jan.ai seems to have very large line heights
- Information density is quite low
- This, together with the small font sizes, makes reading quite difficult
- See comparison of Jan and Hasura below

<img width="1599" alt="image" src="https://github.com/janhq/jan/assets/101145494/209536b1-7f3b-49ba-b99a-87c7a1af1a8d">

## Conversation List to be more Whatsapp/Telegram like?

- See image below

<img width="1598" alt="image" src="https://github.com/janhq/jan/assets/101145494/6ea310e2-ac2c-4614-ae5c-e19db7066cd9">

**Comment by urmauur** [comment]
@dan-jan i'm working on it, my branch are refactor and some cleanup style will push on Monday

**Comment by imtuyethan** [comment]
To catch up on this, @urmauur I have been creating Jan design system on Figma, here's the foundation: 
https://www.figma.com/file/y0V0HuSOHbuWEWcns9nIys/Design-System?type=design&node-id=1048-4216&mode=design

[x] Brand logo (added Nitro logo, refactored Jan logo component)
[x] Font (As we finalized that we're gonna use Inter from now on, please update our website as well)
[] Colors (WIP)
[] Styles (WIP)

**Comment by imtuyethan** [comment]
I'm updating this issue title so it will focus on Jan Desktop App only, since we already had a separate request for Jan.ai website (https://github.com/janhq/internal/issues/37)

**Comment by imtuyethan** [comment]
Will include Nicole's latest feedback to this issue:

A few UI nits & copy fixes for 0.3.1 @Ashley can you help me incorporate & track them in an issue or whatever process you prefer: 
- Ribbon: What’s the book icon supposed to lead to?
- Ribbon: Better icon for Explore Models. Maybe globe? Or try the letter E?
- My Models page: the empty state copy is wrong. Not Ups, You dont  => Oops, you don’t have a model.
- My Models page: let’s download your first model - capitalize the L.
- All Page: Titles should have a space, not MyModels but My Models, same for other pages.
- In Search modal, highlighted rows should be white text, since they have a dark blue background.
- StatusBar: When models are downloading, status bar should say Downloading 4 models (always Verb + subject) instead of 4 - - Downloading model
- Bigger font + color contract for readability

**Comment by imtuyethan** [comment]
This issue will be solved along with new UIkit that @imtuyethan are gonna build up: https://github.com/janhq/internal/issues/51

**Comment by 0xSage** [comment]
Already incorporated in new designs.

**Comment by 0xSage** [comment]
Also copywriting fixed in #750
