### ISSUE TITLE
bug: Failed to load model sometime

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#572]
**Describe the bug**
Load model request is failed
<img width="235" alt="Screenshot_2023-11-09_at_09 56 52" src="https://github.com/janhq/jan/assets/133622055/88c3ca27-5d07-4c78-a426-54ad84c69638">

**To Reproduce**
- Start model, stop then restart, repeat this

**Comment by louis-jan** [comment]
Will reproduce and capture the error output here @tikikun. Please let me know if I can use any other `verbose execution file` to get more output

**Comment by louis-jan** [comment]
Update: Nitro hangs forever (both load model / inference requests can't be sent)

<img width="673" alt="Screenshot 2023-11-09 at 20 58 15" src="https://github.com/janhq/jan/assets/133622055/d549d3bb-a0d5-44d7-a6c6-634e967ab07c">

<img width="977" alt="Screenshot 2023-11-09 at 20 58 20" src="https://github.com/janhq/jan/assets/133622055/19763fa9-1e29-4299-888e-4d30ad560e12">

**Comment by 0xSage** [comment]
@vuonghoainam is there a PR to fix this already? If not, it should be `in progress`. 
In review is more like: "this issue has a fix that needs a peer review, it is blocked until someone looks at it`

**Comment by tikikun** [comment]
I have some recommendations to further debug this issues:
- I recommend to properly get the stddout log during runtime for the inference plugin ( as seen in https://nodejs.org/api/child_process.html ). Since we should have this option when running a subprocess, even in the future with distribution in node, python etc.... 
- @vuonghoainam please provide the current version of nitro being used by the inference plugin (Nitro will support print out nitro version in the 0.3.0 milestone)

**Comment by louis-jan** [comment]
LOGCAT
[stddout.txt](https://github.com/janhq/jan/files/13344803/stddout.txt)

**Comment by louis-jan** [comment]
The latest Nitro versions do not support runtime model reloading. This requires killing and respawning the process to work, but it's quite hacky. We should properly implement an unload feature.
