### ISSUE TITLE
bug: Quitting & deleting Jan should quit/delete Nitro

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#604]
More discussion needed here on exact behavior

States: 

1. User soft quits, i.e. closes the window
2. User hard quits, i.e. presses cmd+q
3. User uninstalls the app

**Comment by louis-jan** [comment]
@linhtran174 & @hiento09 will drive this

**Comment by hiento09** [comment]
![image](https://github.com/janhq/jan/assets/136591877/5f4339b9-690f-4724-b3f5-f7836c89c6c9)
![image](https://github.com/janhq/jan/assets/136591877/935f08ab-5251-4c00-a1e4-83cdc89f6da1)
Since I have installed GPU to my machine and try jan app using nitro GPU, however when I hard quit Jan app, the nitro process is still running.

**Comment by louis-jan** [comment]
Wow, great find. @hiento09

**Comment by 0xSage** [comment]
Also mentioned in #906
