### ISSUE TITLE
Discussion: How to make Node Native Modules available in our Core SDK?

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#910]
**Motivation**
Right now, for an extensions builder to utilize a Node core module, like `path`, `child-process`, our SDK forces them to: 
1. Implement the logic in `/extension/{user-extension}/module.ts`
2. Invoke the logic through a `executeOnMain` call in `/extension/{user-extension}/index.ts`
3. `executeOnMain` is exposed through Core API (which imo is not a great API to expose in Core in the first place)
4. In Core, `executeOnMain` then invokes `invokeExtensionFunc`, i.e. `window.core?.api?.invokeExtensionFunc`
5. During runtime, this invocation emits Electron event: `'extension:invokeExtensionFunc'`
6. This event is handled by Electron `main process`
7. The main process, at last, executes: `return module[method](...args)`
Yikes!

This paradigm is still used by 
- `inference-extensions`
- `monitoring-extension`

This is problematic for several reasons: 
1. Extension Builders shouldn’t have to differentiate btw controller level vs infra level. They should be able to write a single `index.ts`, and trust that the code will run across all Jan supported infra.
2. Extension Builders still able to use Node native libs they are familiar with like `fs`, `path`, `log`, `systeminformation` in `index.ts`
3. We shouldn't have to write helper libraries (like our current core/fs.ts) to grant access to the standard library set.
4. Conversely (3), Extension Builders shouldn't have to learn our Helper library syntax to effectively make extensions.

**Discussion**
1. Can NodeJS "core/built-in" modules be **implicitly exported or piped** via Core?
2. Is there a better way to make base node modules available to the Extension Builder? 
3. Security implications?

**Alternatives**

**Resources**

**Comment by louis-jan** [comment]
### Context
Since we support UMD Module, every extension can be a UMD extension as well. However, the challenge is that we are opening to let Extension Builder import certain CommonJS or Browser modules which could break the runtime. So, the UMD module like Core should not depend on 3rd-party modules but we can provide NodeJS "core/built-in" modules implicitly exported or piped via Core in the same way as fs. It would take a lot of efforts to build APIs wrapper around them though.

The simplest approach for our use cases, in terms of the most straightforward solution, is to wrap `process` in Core like what we did with fs.

There is another approach that would involve efforts in designing the framework, but it would be better for scalability. This could also cause some bloating of the NodeJS architecture.

### Built-in extensions
Built-in extensions could run entirely on the Node runtime instead of Browser. Extensions running on the Node process will send events to the app's frontend.
- Most of the use cases are on Node runtime.
- Rework on events to create a pipeline between Node and Browser processes (currently only Browser).
- Implement base extensions on Browser to communicate with Customized/Extension implementations running on Node runtime.

### Extended extensions
Similar to Visual Code Extension Architecture, Extension Builder could define the host runtime (default is Node).
https://code.visualstudio.com/api/advanced-topics/extension-host

@0xSage

**Comment by 0xSage** [comment]
Thank your for the clear explanation. Your option 1 seems like a subset of option 2. Of course, giving builders the ability to define `extensionKind` is the most extensible, i.e. they declare it in our `extension.json` manifest. But, can I understand the difference in effort between the two?

Is this the type of complexity we want to take on at this point @dan-jan ?

**Comment by louis-jan** [comment]
Server side extension arch would cost us a couple of sprints and subsequence features such as broadcasting events across processes.

**Comment by 0xSage** [comment]
> Server side extension arch would cost us a couple of sprints and subsequence features such as broadcasting events across processes. I would love to just start with the first one and scale to 2 later.

Yep makes sense.

**Comment by dan-jan** [comment]
@0xSage This discussion should be summarized in docs. Tagging this to Milestone 0.4.2

**Comment by 0xSage** [comment]
More or less solved by app pod
