### ISSUE TITLE
bug: using remote model overrides thread history with other models!

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#997]
**Describe the bug**
<img width="1406" alt="image" src="https://github.com/janhq/jan/assets/69952136/e27b586a-cec5-4f5c-a33a-3758f93ed52e">

**To Reproduce**
1. Chat with mistral
2. Create new thread
3. Chat with "chatgpt 3.5"
4. Go back to previous Mistral thread
5. See the rightside panel > model section > now says `chatgpt 3.5` instead of `mistral`
6. Go to system monitoring > stop chatgpt 3.5 > things return to normal

**Expected behavior**
1. Chatting with remote models should not start or stop anything.
2. You can concurrently chat with n remote models
3. And your local models should still be running.
4. When I do chat with a remote model, it shouldn't override all other threads rightpanels.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac m1 16gb
 - Version: 0.4.1

**Additional context**

**Comment by urmauur** [comment]
@0xSage fixed issue right panel regarding selected model with this [PR](https://github.com/janhq/jan/pull/1001)

**Comment by louis-jan** [comment]
The issue is not just on remote model but even switching between local models. The start stop action is just a fake action for now that hacked by @vuonghoainam to make it work, we will have proper state handling for remote model later. 

Let's scope down the expected behavior so we can close with the fix above: 
- Switch between threads should show corresponding active model.

**Comment by louis-jan** [comment]
Fixed the major issue
